name: capybara
favicon: null
layout_spectrum: 0.45313443522900343
typography_spectrum: 0.9671165107283741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9746385840699077
  lightness: 0.7482037406880409
  saturation: 0.30445503164082766
  rhythmicContrast: 0.3196217082440853
purpose: []
